" .vimrc

set nocompatible

" Plugins
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'SirVer/ultisnips'
Plugin 'scrooloose/nerdtree'
Plugin 'kien/ctrlp.vim'
Plugin 'sjl/gundo.vim'

call vundle#end()
filetype on
filetype plugin on
filetype indent on

syntax on
set history=400
set showcmd
set autowrite
set hidden
set virtualedit+=block
set mouse=a
set scrolloff=4
set backspace=indent,eol,start
set showmatch
set wildmenu
set wildmode=list:longest
set title

runtime macros/matchit.vim

let mapleader = ","

" Status line
set laststatus=2
set ruler

" Interface
set background=dark
set relativenumber
set number

" Jump to last position when reopening a file:
autocmd BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif

" Searching
set magic " use expressions in patterns by default
set hlsearch " highlight search terms
set incsearch		" Incremental search
set ignorecase
set smartcase		" Do smart case matching

" Indenting
set tabstop=4
set shiftwidth=4
set noexpandtab
set autoindent
set smartindent
set cindent
set smarttab

" Shortcuts
map <F1> :NERDTreeToggle<CR>
map <F2> :GundoToggle<CR>

map <F5> :make<CR>

nmap <leader>t :tabnew<CR>

" fold/unfold all folds
map F :let &fen = !&fen<CR>

" Open quick fix window on error
autocmd QuickFixCmdPost [^l]* nested cwindow
autocmd QuickFixCmdPost    l* nested lwindow

